version: '3'

services:
  transcendence:
    container_name: transcendence
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy  

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 10