# Generated by Django 4.2.7 on 2023-12-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainTestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='blockchain_hash',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
