# Generated by Django 4.2.7 on 2023-12-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_name', models.CharField(max_length=255)),
                ('player1_points', models.PositiveIntegerField()),
                ('player2_name', models.CharField(max_length=255)),
                ('player2_points', models.PositiveIntegerField()),
            ],
        ),
    ]
