# Generated by Django 4.2.7 on 2023-12-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id_semi_1', models.PositiveIntegerField()),
                ('match_id_semi_2', models.PositiveIntegerField()),
                ('match_id_final', models.PositiveIntegerField()),
                ('tournament_end_timestamp', models.DateTimeField()),
                ('tournament_duration_secs', models.PositiveIntegerField()),
            ],
        ),
    ]
