# Generated by Django 4.2.7 on 2023-12-13 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='game_duration_secs',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='game_start_timestamp',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
