# Generated by Django 4.2.7 on 2024-01-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_tournamentdata_player_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentdata',
            name='blockchain_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
