# Generated by Django 4.2.7 on 2023-12-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_gamedata_game_duration_secs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='game_duration_secs',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='game_start_timestamp',
            field=models.DateTimeField(),
        ),
    ]
