# Generated by Django 4.2.7 on 2023-12-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_alter_gamedata_game_duration_secs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamedata',
            old_name='game_start_timestamp',
            new_name='game_end_timestamp',
        ),
    ]
