# Generated by Django 4.2.7 on 2023-12-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_rename_game_start_timestamp_gamedata_game_end_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='is_tournament_game',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
